# Build PDF & ePub
formats:
    - htmlzip
    - epub
    - pdf
python:
    pip_install: true
    version: 3.5
    extra_requirements:
        - recommonmark
        - pygments-markdown-lexer
        - sphinx-intl
requirements_file: ./stable-req.txt